/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.rkr1410.pascal;

public class App {
    private static App App = new App();
    private static App App2 = new App();
    public App() {
        System.out.println(App);
        System.out.println(App2);
    }

    public static void main(String[] args) {

    }
}
